var str = "  NGuYen   vAn   a  ";
console.log(str);
str = str.toLowerCase();
str = str.trim();
str = str.replace("   ", " ");
str = str.replace("   ", " ");
console.log(str);
str1 = str.slice(0,6);
str1 = str1.replace("n", "N");
console.log(str1);
str2 = str.slice(6,11);
str2 = str2.replace("v", "V");
console.log(str2);
str3 = str.slice(11,12);
str3 = str3.toUpperCase();
console.log(str3);
str = str1 + str2 + str3;
console.log(str);
document.getElementById("result").innerHTML = str;
